name: Plan on PR
author: robert@parkside.app
description: An action to plan Terraform configs.
inputs:
  dirs:
    description: 'Colon delimited list of directories to process.'
    required: true
  base:
    description: 'Base branch of the PR'
    required: false
  cmd:
    description: 'Command to run.  Valid choices are `plan | apply'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '${{ inputs.command }}'