name: Parkside GitOps Actions
author: robert@parkside.app
description: A set of Actions for testing, integrating, deploying, and releasing IaC.
inputs:
  cmd:
    description: 'Command to run.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '${{ inputs.command }}'