on: [pull_request]

env:
  TERRAFORM_VERSION: 0.12.16
  KUBECTL_VERSION: 1.17.0
  HELM_VERSION: 3.0.2
  DIRENV_VERSION: 2.20.0
  ENVKEY_VERSION: 1.2.9
  AWS_IAM_AUTHENTICATOR_VERSION: 1.14.6
  ARTIFACTS_DIR: /github/workspace/artifacts
  TERRAFORM_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
  SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: parkside-securities/terraform-action/plan
        id: plan
        with:
          dirs: parkside-bastion:parkside-billing:parkside-compliance:parkside-core-services:parkside-data-science:parkside-dev:parkside-logging:parkside-master:parkside-network:parkside-ops:parkside-prod:parkside-secops:parkside-staging
      - uses: actions/upload-artifact@v1
        if: steps.plan.outputs.errors == 0
        with:
          name: artifacts
          path: artifacts
