on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Debug
        run: |
          git --no-pager branch -a